version: '3'
services:
  openproject:
    #image: openproject/community:8.3
    build: ./
    restart: always
    volumes:
      - ./openproject/pgdata:/var/openproject/pgdata
      - ./openproject/static:/var/openproject/assets
  web:
    image: nginx:alpine
    restart: always
    environment:
      SECRET_KEY_BASE: <somesecretkeybase>
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    ports:
      - "443:443"
    depends_on:
      - openproject
